# Site settings
title:          Son92
description:    "Blog của Son92"
baseurl:        ""
url:            "https://son92.io.vn"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Son92
  url:          https://son92.io.vn
  email:        son92@vozmail.top

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title-:short_year-:month-:day
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
